services:
  pwa:
    build:
      context: .
      dockerfile: Dockerfile

    image: pwa-homelab:latest
    container_name: pwa-homelab

    restart: unless-stopped

    networks:
      - homelab

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=homelab"

      - "traefik.http.routers.pwa.rule=Host(`pwa.homelab`) || Host(`192.168.15.7`)"
      - "traefik.http.routers.pwa.entrypoints=web"

      - "traefik.http.services.pwa.loadbalancer.server.port=80"

networks:
  homelab:
    external: true